services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: grocery-app-container
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # - OPENSEARCH_HOST=http://opensearch:9200
      - NODE_ENV=development

    env_file:
      - .env
    # depends_on:
    #   - opensearch
#   opensearch:
#     image: opensearchproject/opensearch:2.11.0
#     # container_name: my-opensearch
#     environment:
#       - cluster.name=opensearch-cluster
#       - discovery.type=single-node
#       - "DISABLE_SECURITY_PLUGIN=true"
#       - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
#     ports:
#       - "9200:9200"
#     volumes:
#       - opensearch-data:/usr/share/opensearch/data

# volumes:
#   opensearch-data:
